
# Pull base image
# ---------------
FROM docker.bintray.io/jfrog/artifactory-oss:6.7.3

# Maintainer
# ----------
MAINTAINER Allan Thrane Andersen <einheriii@gmail.com>

# Define Artifactory volume
VOLUME /var/opt/jfrog/artifactory