
# Pull base image
# ---------------
FROM jfrog-docker-registry.bintray.io/jfrog/artifactory-oss

# Maintainer
# ----------
MAINTAINER Allan Thrane Andersen <einheriii@gmail.com>

# Define Artifactory volumes
# https://www.jfrog.com/confluence/display/RTF/Running+with+Docker
VOLUME /artifactory/data
VOLUME /artifactory/logs
VOLUME /artifactory/backup
VOLUME /artifactory/etc
