
# Pull base image
# ---------------
FROM registry:2

# Maintainer
# ----------
MAINTAINER Allan Thrane Andersen <einheriii@gmail.com>

# Define registry volumes
# https://docs.docker.com/registry/deploying/
VOLUME /var/lib/registry

EXPOSE 5000

