
# Pull base image
# ---------------
FROM registry:2

LABEL maintainer="einheriii@gmail.com"

# Define registry volumes
# https://docs.docker.com/registry/deploying/
VOLUME /var/lib/registry

EXPOSE 5000

